Deltares/hydromt_fiat

- hydromt_fiat/__init__.py
- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/buildings.py
- Bug fix DataArray.where() in building.py workflow
- Corrected error messages in fiat.py
> Minor corrections

- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/exposure_vector.py
- hydromt_fiat/workflows/vulnerability.py
Small update after the PR review of #124
> Pr#124 updates

- hydromt_fiat/api/data_types.py
- hydromt_fiat/api/exposure_vm.py
- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/exposure_vector.py
- tests/test_update_max_potential_damage_user_data.py
-  update ground floor height term "method" to "gfh_method"
-  update ground floor height term "attr_name" to "attribute_name"
> #240 update ground floor height term "method" to "gfh_method"

- hydromt_fiat/api/data_types.py
- hydromt_fiat/api/exposure_vm.py
- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/exposure_vector.py
- tests/test_update_max_potential_damage_user_data.py
Allow user to use own damage data
> #241 damage values tab

- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/aggregation_areas.py
- Take out "filter"for roads as this prevented the function from running. 
- Allow overlapping features because we run into issues with the census data
> #71 extra tab additional attr

- hydromt_fiat/workflows/exposure_vector.py
now polygon is first trannsformed to the exposure crs to make sure selection is correct
> polygon selection crs bug fix

- hydromt_fiat/__init__.py
- pyproject.toml
bump version to 0.3.0
uploaded to pypi
> Update hydrom_fiat to upload to the pip database

- hydromt_fiat/api/data_types.py
- hydromt_fiat/api/exposure_vm.py
- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/exposure_vector.py
- add unit as variable for ground elevation setup
- convert if units do not align (feet and meters)
> #294 dem unit conversion

- hydromt_fiat/api/data_types.py
- hydromt_fiat/api/exposure_vm.py
- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/exposure_vector.py
This feature is needed for Floodadapt but in hydromt fiat it can destroy model outputs for other purposes.
Default value = False
> add bool parameter to decide whether convert or not convert bf into points

- hydromt_fiat/interface/spatial_joins.py
percapitalincome changed to percapitaincome
> typo fix for equity variable

- hydromt_fiat/workflows/exposure_vector.py
fixed bug where now two variables are returned from join_exposure_aggregation_areas
> fixed bug with aggregation areas join

- hydromt_fiat/workflows/exposure_vector.py
Reverts Deltares/hydromt_fiat#341
> Revert "small updates"

- hydromt_fiat/fiat.py
- tests/test_equity_data.py
Since the svi allocation to the buildings is a spatial join, not the information is added to the configuration.
> updated svi creation with spatial join info

- hydromt_fiat/api/data_types.py
- hydromt_fiat/api/exposure_vm.py
- hydromt_fiat/api/hydromt_fiat_vm.py
- hydromt_fiat/api/vulnerability_vm.py
- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/exposure_vector.py
> Road updates

- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/exposure_vector.py
> Region fix

- hydromt_fiat/api/exposure_vm.py
- hydromt_fiat/workflows/exposure_vector.py
A basic model (buildings and roads) can be loaded in into the model builder (without User input and spatial joins).
Note: Also added a bugfix to update the NSI classification with user input
> 369 enable to read in existing model in gui

- hydromt_fiat/fiat.py
> Write geom fix

- hydromt_fiat/workflows/exposure_vector.py
> Fix update model parameters roads

- hydromt_fiat/fiat.py
The change ensures that a model is written even when there is no region available.
> updated write_geoms method to check if region is available

- docs/_static/fiat_logo.svg
- hydromt_fiat/version.py
It's been a while since the latest release, so I think making a new release is a good idea. Sarah ran the tests on the floodadapt side and everything on the main branch seems to work, so I'd like to release a known good version so we have something to fall back on when we start improving.
> Release version v0.4.0

- hydromt_fiat/workflows/exposure_vector.py
> Corrected ground flood height analysis for new composite areas and allow for multiple heights per polygon

- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/damage_values.py
- hydromt_fiat/workflows/exposure_vector.py
add workflow for user damage input through csv file
> Up2030 generalize damage curves

- hydromt_fiat/fiat.py
spatial joints were not read into the model when fm.read()
added spatial joints to read_geoms
> Read spatial joints

- hydromt_fiat/workflows/exposure_vector.py
the indexing would create duplicated object ids for roads and buildings which would cause the building point geometry to be overwritten as a linestring geometry
> reindex exposure

- hydromt_fiat/fiat.py
- pyproject.toml
Method to create a default aggregation grid if no aggregation is provided and aggregation_area_fn is set to "default". 
Creates a  vector grid based on the resolution (user input res_x, res_y)
> Create default aggregation areas grid

- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/exposure_vector.py
Allows for defining a name for the new composite area geometry. A small change in the code for that part took place to simplify it a bit.
> Updates new composite area

- src/hydromt_fiat/components.py
- src/hydromt_fiat/data/registry.json
- src/hydromt_fiat/fiat.py
- tests/conftest.py
- tests/test_component.py
> V1: Update RegionComponent

- docs/api.rst
- pixi.lock
- pyproject.toml
- src/hydromt_fiat/data/registry.json
- src/hydromt_fiat/fiat.py
- src/hydromt_fiat/utils.py
- src/hydromt_fiat/workflows/__init__.py
- src/hydromt_fiat/workflows/utils.py
- src/hydromt_fiat/workflows/vulnerability.py
- tests/conftest.py
- tests/test_model.py
- tests/workflows/test_vulnerability.py
> V1 Setup Vulnerability

- src/hydromt_fiat/fiat.py
- src/hydromt_fiat/utils.py
> Typing fixing

- examples/data_catalog.yml
- src/hydromt_fiat/drivers/osm_driver.py
- tests/test_osm_driver.py
Fixes #463
Added an example data catalog that also contain the data sources for osm data assets.
In addition to the above I also added another check to OSMDriver.read method that checks if the mask is not None and gives a clear error message when it is None.
> V1 example datacatalog

- src/hydromt_fiat/errors.py
- src/hydromt_fiat/fiat.py
- src/hydromt_fiat/workflows/hazard.py
- tests/test_model.py
- tests/workflows/test_hazard.py
> V1 add hazard data

- src/hydromt_fiat/fiat.py
- src/hydromt_fiat/workflows/vulnerability.py
- tests/conftest.py
- tests/test_model.py
- tests/workflows/test_vulnerability.py
Fixes exposure typing and naming
Code.
No.
> V1 Small vulnerability update

- src/hydromt_fiat/fiat.py
- tests/test_model.py
> V1 added config set for hazard grids with multiple data vars

- src/hydromt_fiat/fiat.py
- src/hydromt_fiat/utils.py
- src/hydromt_fiat/workflows/hazard.py
- src/hydromt_fiat/workflows/vulnerability.py
- tests/test_utils.py
- tests/workflows/test_hazard.py
- tests/workflows/test_vulnerability.py
> V1 Units fix

- src/hydromt_fiat/fiat.py
- src/hydromt_fiat/workflows/hazard.py
- tests/conftest.py
- tests/workflows/test_hazard.py
Fixes according to design document
Followed the example from the exposure_grid branch (#486) by @Tjalling-dejong.
Added a test specifically for grid_like
No.
> V1 Update hazard to design

- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/aggregation_areas.py
- hydromt_fiat/workflows/exposure_vector.py
The set up equity function caused issues in the setup_aggregation function because it creates lists of the label and attribute names, so that needed adjustment. 
Also the roads crashed in roads.empty when there were no roads. 
> Bugfix empty roads

- src/hydromt_fiat/components/exposure_geom.py
- src/hydromt_fiat/components/exposure_grid.py
- src/hydromt_fiat/components/region.py
- src/hydromt_fiat/data/registry.json
- src/hydromt_fiat/fiat.py
- src/hydromt_fiat/utils.py
- src/hydromt_fiat/workflows/__init__.py
- src/hydromt_fiat/workflows/damage.py
- src/hydromt_fiat/workflows/exposure_geom.py
- src/hydromt_fiat/workflows/exposure_grid.py
- src/hydromt_fiat/workflows/vulnerability.py
- tests/components/test_exposure_geom_component.py
- tests/components/test_exposure_grid_component.py
- tests/conftest.py
- tests/workflows/conftest.py
- tests/workflows/test_damage.py
- tests/workflows/test_exposure_geom.py
- tests/workflows/test_exposure_grid.py
- tests/workflows/test_hazard.py
- tests/workflows/test_vulnerability.py
Fixes current linking issues
Simplified the linking at the vulnerability stage, which trickles down to the exposure setup stages. Added global strings for easier tracking of identifiers. 
> V1: Linking improvement

- hydromt_fiat/version.py
- pyproject.toml
bump version 0.5.6
Fixes #<issue number>
> remove version specifier for dask

- .github/workflows/docs.yml
- .github/workflows/linting.yml
- .github/workflows/lock.yml
- .github/workflows/test.yml
- .github/workflows/test_single.yml
Fixes last workflow issues from v1
Literally just adjust some text.
> Fix: update CI to point to main and add SHA's
