- hydromt_fiat/workflows/exposure_vector.py
buildings geodataframe extraction
> Small changes in object selection

- hydromt_fiat/fiat.py
units were not correctly passed to the exposure model. Furthermore, added a check in case the unit attribute is a pydantic model to get its string value
> make sure unit are correctly parsed to the exposure model

- hydromt_fiat/workflows/exposure_vector.py
Current Issue
When the user uses a polygon file in the finished floor height input the intersection method copies all columns of the new gdf and places them into the exposure_db, which causes an error. Also, if columns have the same name in the original exposure_db and new damage gdf the function appends "_left" , "_right"
Solution
if method == "intersection" all columns except for the new damage column and geometry (needed for spatial joint) are removed before the spatial joint of the 2 dataframes. All columns with "_left" appended are renamed to the original exposure_db name
> bugfix intersection method when polygons added as finished floor height

- hydromt_fiat/workflows/exposure_vector.py
**Current Issue**
When the user uses a polygon file in the damage input the intersection method copies all columns of the new gdf and places them into the exposure_db, which causes an error. Also, if columns have the same name in the original exposure_db and new damage gdf the function appends "_left" , "_right"
**Solution**
if method == "intersection" all columns except for the new damage column and geometry (needed for spatial joint) are removed before the spatial joint of the 2 dataframes. All columns with "_left" appended are renamed to the original exposure_db name
> udate damage intersection method

- hydromt_fiat/api/hydromt_fiat_vm.py
- hydromt_fiat/workflows/exposure_vector.py
After a quickbuild or "model from scratch" is built and the user wants to update any parameters, 
the model will automatically updated after clicking "add to model" and the user does not create the model another time manually.
DelftDashboard PR: https://github.com/Deltares-research/DelftDashboard/pull/97
Note:
Max Potential Damages not implemented yet because it might take more effort due to content/structure
> #70 update values after model built

- hydromt_fiat/api/data_types.py
- hydromt_fiat/api/exposure_vm.py
- hydromt_fiat/api/model_vm.py
- hydromt_fiat/fiat.py
- hydromt_fiat/interface/config.py
- hydromt_fiat/workflows/exposure_vector.py
add the currency to the settings.toml file and the exposure buildings model.
> #289 add damage unit

- hydromt_fiat/workflows/exposure_vector.py
Corrected raise by datum method:
Before it was checking if the ground flood height is larger than the raise by value value and if not it was giving the ground floor height the raise by value.
The corrected method checks if the total elevation of the object (**ground elevation + ground floor height**) is smaller than the raise by value and if yes, it changes the ground floor height to reach that level.
> corrected raise by for datum ref

- hydromt_fiat/workflows/aggregation_areas.py
Now the first value of the zones is selected.
Should we support different options for the user to select or out of budget reasons leave it that way?
> dont allow multiple values, select first

- .github/workflows/publish-to-pypi.yml
TODO:
For both: pypi(https://pypi.org/project/hydromt_fiat/) & test_pypi (https://test.pypi.org/project/hydromt_fiat/)
add trusted publisher -> github -> this repo, environment = release
make a token for this repo
go to settings -> environment -> environment secrets
paste the correct token into: PYPI_TOKEN or TEST_PYPI_TOKEN
> publish workflow

- hydromt_fiat/workflows/aggregation_areas.py
There was a bug when multiple values were available for an object. Then a transformation to an integer was taken place, which cannot happen e.g. for sting variables (which is quit commonly the case with aggregation areas). 
@Santonia27, if there was not a specific reason to have that, I have now changed that to a general scematization that just takes the first value from a list, independent of the type.
> fixed bug with multiple aggregation values type

- hydromt_fiat/workflows/equity_data.py
in the PR #296, the index was used to update the names of the block groups to strings, but if there were more than one counties that needed to be merged here:
https://github.com/Deltares/hydromt_fiat/blob/361af602595a67eed3697f5a7bdd6fa073ecac1e/hydromt_fiat/workflows/equity_data.py#L188
there were duplicated indices. 
Now the indices are reseted so it should not be a problem.
> corrected bug with indexing of block groups

- hydromt_fiat/workflows/exposure_vector.py
- tests/test_update_max_potential_damage.py
It seems that for a lot of the methods with respect to applying changes (elevating, changing max damage etc.) the indexing was not implemented in a safe way, assumng that always exposure objects are in asceding order based on Object ID.
This needs more attention but I started for now with some corrections.
> fixed bugs with indexing

- README.rst
The pypi version of hydromt fiat has a bug and is not running correctly. 
e need to update the versoin and make a new stable release!
Until then I updated the docs to install hydromt directly from the repo, same as it is done in fiat. 
I followed the installation process on my private machine and was finally able to run the JRC global notebook. (This works with the developer installation but not with the pip install hydromt fiat)
> Change readme

- .gitattributes
- .gitignore
- pixi.lock
- pixi.toml
- pyproject.toml
I've added a `pixi.toml` file, that I've put together manually because there were some inconsistencies between the `pyproject.toml` and the various `evironment.yml` files. I decided to create it along side the exiting ones so that we can try this out without immediately breaking other's workflows. At some point it might be worth discussing moving to pixi entirely. At least for now I think this is okay
> Make installing through pixi possible

- hydromt_fiat/api/hydromt_fiat_vm.py
- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/damage_values.py
- hydromt_fiat/workflows/exposure_vector.py
1. fix gfh to mpd (damages)
2. remove count and replace with zip in mpd
3. add workflow to add user damages with csv file and translation file (open for suggestions for improvement)
> fix gfh to mpd (damages) and remove count and replace with zip

- hydromt_fiat/workflows/exposure_vector.py
There was a bug that did not allow for one of the composite areas to not be elevated in case it was already at high ground. This required to generalize the way the the raise_by varianle type was interpreted.
> Elevating new composite areas based on base flood maps bug fix

- hydromt_fiat/api/data_types.py
- hydromt_fiat/fiat.py
- hydromt_fiat/workflows/damage_values.py
- hydromt_fiat/workflows/exposure_vector.py
convert jrc damage values from eur 2010 to US dollars 2010
> Currency conversion jrc

- hydromt_fiat/workflows/aggregation_areas.py
- hydromt_fiat/workflows/exposure_vector.py
- tests/test_setup_new_composite_area_divided_aggregation.py
> fix new development areas

- hydromt_fiat/workflows/exposure_vector.py
fixed bug for when I single geometry file is available where it was assumed that objects have the same order in the exposure table and geometry file
Fixes #<issue number>
> fixed bug in get_full_gdf method

- hydromt_fiat/fiat.py
- hydromt_fiat/version.py
This fix makes sure that during the config create, for each input file there will be an explicit output with the same name as the input as a geopackage format.
> ensures that for each input geometry there is an output with the same name
